version: '3'
services: 
  mysql:
    image: mysql:5.7.29
    container_name: cms-mysql
    tty: true
    stdin_open: true
    environment:
      MYSQL ROOT PASSWORD: "root"
      MYSQL_PASSWORD: "ThePassword" MYSQL_USER: "speuser"
      MYSQL DATABASE: "spe"
    network_node: bridge
