---
- name: Pull Docker Image and Deploy It
  hosts: SlaveNodes
  vars:
          ansible_python_interpreter: /usr/bin/python3
  become: yes
  become_method: sudo
  tasks:
          - name: Pull repo
            shell:
                    chdir: /tmp
                    cmd: git clone https://github.com/adrijsharma0408/Classroom-Management-IIITB.git
                    listdir: ls -l
            
          - name: Run the cleaning script
            shell: ./scriptCleanSH.sh 
           
          - name: Ensure that Docker service is enabled
            service:
                    name: docker
                    state: started

          - name: Pull the Docker Image
            docker_image:
                    name: adrijsharma/classroom_management_iiitb:latest
                    source: pull      

          - name: Run the Container
            shell: docker run -t -p 8082:8082 --name cms-springboot --link cms-mysql:mysql -d adrijsharma/classroom_management_iiitb
            
        
